server:
    port: 9001

#Redis配置
spring:
    datasource:
        username: root
        password: kong@1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://106.12.56.87:3308/febs_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    redis:
        database: 6  #Redis索引0~15，默认为0
        host: 106.12.56.87
        port: 6379
        password:  qwer@tyui #密码（默认为空）
        jedis: # 这里标明使
            pool:
                max-active: 8   #连接池最大连接数（使用负值表示没有限制）
                max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 5     #连接池中的最大空闲连接
                min-idle: 0     #连接池中的最小空闲连接
        timeout: 10000    #连接超时时间（毫秒）


logging:
    # Debug打印SQL
    level.com.wang.mapper: debug

# AES密码加密私钥(Base64加密)
encryption:
    encryptAESKey: V2FuZzkyNjQ1NGRTQkFQSUpXVA==
  # JWT认证加密私钥(Base64加密)
    encryptJWTKey: U0JBUElKV1RkV2FuZzkyNjQ1NA==
  # AccessToken过期时间-5分钟-5*60(秒为单位)
    accessTokenExpireTime: 300
  # RefreshToken过期时间-30分钟-30*60(秒为单位)
    refreshTokenExpireTime: 1800
  # Shiro缓存过期时间-5分钟-5*60(秒为单位)(一般设置与AccessToken过期时间一致)
    shiroCacheExpireTime: 300