spring:
  profiles:
    active: dev
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#freemarker模板配置
  freemarker:
    suffix: .ftl
    cache: false
    charset: UTF-8
    contentType: text/html
    requestContextAttribute: ctx
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      defaultEncoding: UTF-8
      url_escaping_charset: UTF-8
      locale: zh_CN
  http:
    activiti:
      check-process-definitions: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  servlet:
    session:
      timeout: 30
---
#环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://106.12.56.87:3308/activiti6?useUnicode=true&useSSL=false&amp;characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: kong1234

server:
  port: 8080