

spring:
  redis:
    database: 5
    host: 81.70.15.115
    # Redis服务器连接端口
    port: 16379
    # Redis服务器连接密码（默认为空）
    password: qwertyui
    # 连接池最大连接数（使用负值表示没有限制）
    jedis.pool.max-active: 1000
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    jedis.pool.max-wait: -1
    # 连接池中的最大空闲连接
    jedis.pool.max-idle: 300
    # 连接池中的最小空闲连接
    jedis.pool.min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000